export default {
    Sessions: '/base/sessions',
    UploadImg: '/upload/img',
    Admin: '/admin',
    News: '/news',
    User: '/user',
    UserResume: '/user-resume',
    UserLikeJob: '/user-like-job',
    Company: '/company',
    CompanySearch: '/company/search',
    CompanyJob: '/company-job',
    CompanyJobSeearch: '/company-job/search',
    Job2Resume: '/job-to-resume',
    HomeStatistics: '/news/home-statistics',
    HomeFeedback: '/news/home-feedback',
}
